# Generated by Django 3.0.5 on 2020-05-11 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 5, 11, 14, 6, 56, 468598))),
                ('articleimage', models.ImageField(default='', upload_to='articleimages')),
            ],
        ),
    ]
